apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  config.txt: |
    PORT=3000
    SERVER_ADDR= 0.0.0.0
    CA_PATH=""
    SSL_KEY=""
    SSL_CERT=""
    INSECURE= "true"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step-template-ex
spec:
  params:
    - name: cfg-name
      default: "my-configmap"
    - name: volume-name
      default: "my-config"
    - name: volume-mount-path
      default: "/etc/my-service-config/"
  volumes:
    - name: $(params.volume-name)
      configMap:
        name: $(params.cfg-name)

  stepTemplate:
    env:
      - name: "FOO"
        value: "bar"
    volumeMounts:
      - name: $(params.volume-name)
        mountPath: $(params.volume-mount-path)
  
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/bin/bash
        echo "FOO is $FOO"
        echo
        cat /etc/my-service-config/config.txt
    
    - name: step2
      image: ubuntu
      script: |
        #!/bin/bash
        echo "FOO is $FOO"
        echo 
        cat /etc/my-service-config/config.txt
      env:
        - name: "FOO"
          value: "baz"