apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-local-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      